export const ActionTypes = {
  ADD_ITEM: "ADD_ITEM",
  SELECT_ITEM: "SELECT_ITEM",
  ADD_NEW_LIST: "ADD_NEW_LIST",
  RESET_SELECTED: "RESET_SELECTED",
  INCREASE_TIMER: "INCREASE_TIMER",
  DECREASE_TIMER: "DECREASE_TIMER",
};
